import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navebar from "../components/Navebar";
import Footer from "../components/footer";
import GymProvider from "../app/contex/gymContex"
import { ToastProvider } from "../components/ToastContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white" suppressContentEditableWarning={true} cz-shortcut-listen="true">
        <GymProvider>
          <ToastProvider>
            <Navebar />
            {children}
            <Footer />
          </ToastProvider>
        </GymProvider>
      </body>
    </html>
  );
}
